## GET

# GET http://localhost:3000/api/v1/aluno

## POST

POST http://localhost:3000/api/v1/aluno
Content-Type: application/json

{
 "matricula": "103",
 "nome": "Mateus",
 "curso": "Sistemas de Informação",
 "ativo": true
}

## PUT do que postei em cima

#PUT http://localhost:3000/api/v1/aluno/288d51af-3928-4a72-856f-991f4942701e
#Content-Type: application/json

#{
#  "nome": "Vitor Gabriel"
#}

## DELETE no "Vitor Gabriel"

#DELETE  http://localhost:3000/api/v1/aluno/288d51af-3928-4a72-856f-991f4942701e
#Content-Type: application/json